export const AUTH_COOKIE = "vericore_refresh_token";

export const OTP_PURPOSE = {
  REGISTRATION: "REGISTRATION",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RECOVER_USER_ID: "RECOVER_USER_ID",
  RECOVER_EMAIL: "RECOVER_EMAIL"
};

export const USER_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED"
};